# Generated by Django 3.1.7 on 2021-05-02 13:56

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(blank=True, to='actors.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 5, 2, 13, 56, 49, 216947, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
